name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get tag version
      id: prep
      run: |
        if [[ $GITHUB_REF == refs/heads/main ]]; then
          echo "::set-output name=version::latest"
        else
          echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
        fi
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/url-to-png:${{ steps.prep.outputs.version }}
